### ISSUE TITLE
Please add compatibility with [insert mod here].

### ISSUE THREAD

**Issue by M4thG33k** [M4thG33k/TombManyGraves2#1]
If there is a specific mod with an interaction that isn't currently compatible with Tomb Many Graves, feel free to mention what exactly doesn't work. (For example, if there is a "soulbound" mechanic from a mod, a backpack mod, or a mod that adds extra inventory slots that the graves don't know about.

EDIT: The reason this is here is because I'm not actively playing MC 1.11.2, so I'm not entirely aware of which mods have updated to this version or not. Letting me know about them allows be to add compatibility. :-)

**Comment by Rosethorns** [comment]
Wearable Backpacks by Copygirl
Currently when you die the content of the backpack will spill on the ground and the backpack will stay in your grave.
Secondly. After you pick up your grave the empty equipped backpack will not be useable until you put it down and pick it back up. 

Cheers!

**Comment by M4thG33k** [comment]
Message received. I'll work on adding compatibility. Thanks!

**Comment by M4thG33k** [comment]
@Rosethorns Version 3.0.2 was just uploaded to Curse, adding compatibility with Wearable Backpacks. Let me know if any weird bugs arise. (I tested literally everything I could think of that could break it.) :-)

**Comment by Rosethorns** [comment]
You are awesome. Thank you!

**Comment by TheLimePixel** [comment]
Aether Legacy. It has its own Baubles-like inventory.

**Comment by flannerby** [comment]
In addition to Aether Legacy, Aether II and Galacticraft have their own equipment spaces and do not currently work with the latest version of TMG2. Items are dropped rather than stored.

**Comment by TheLimePixel** [comment]
Aether II is for 1.7.10. This mod is for 1.11.2.

**Comment by SjetCraft** [comment]
There is a soulbound upgrade/enchant in [Levels](https://mods.curse.com/mc-mods/minecraft/235552-levels). I have been tried adding the mod's version of soulbound to the config but it did not work.

**Comment by M4thG33k** [comment]
Sorry for being off-grid as of late, I'll try fixing some of these issues today.
@SjetCraft I'll look into the Levels soulbound upgrade.
@EmosewaGamer & @flannerby , I'll look into adding complete compatibility with those mods, but I may just end up adding a "blanket" fix for now (which will add partial compatibility with any mod with extra inventory slots) which will do a secondary check after the grave has formed for remaining items when they drop and add them to the grave - these items would not be placed in their original slots, but they also wouldn't drop on the ground.

**Comment by M4thG33k** [comment]
@SjetCraft Levels compatibility will be in the next version for 1.11.2.

**Comment by M4thG33k** [comment]
@EmosewaGamer & @flannerby , a "hacky" fix to mod incompatibility will be in the next version. When the player respawns after death (when a valid grave has formed), the grave itself will search in a 4-block radius for any items on the ground and grab them. There are, obviously, scenarios in which items can still be lost (lava/void deaths for one), but this will cut down on the number of lost items.

**Comment by Darkosto** [comment]
Heya @M4thG33k !

Any chance to add Twilight Forest support for inventory lists in 1.12.1? 

Thank you :D 
Darkosto

**Comment by M4thG33k** [comment]
Hey @Darkosto (another name I actually recognize from the MC community!). What interaction between the lists and Twilight Forest do you need added? Does TF add extra slots or what? Thanks!

**Comment by Darkosto** [comment]
I've been doing some testing and it seems as inventory lists do not spawn after a player dies when in the Twilight Forest. I can show you on stream if you have time at some point :)

**Comment by M4thG33k** [comment]
That gives me a better idea what to look for; a few more questions before I actually download stuff and start working (since it will help me narrow down the issue): 1) Can you sleep in the TF? 2) Have the lists appeared at either spawn for the overworld or TF?

**Comment by Darkosto** [comment]
Sure!

1. Yes, using a bed works in the TF (you won't pass time but it does set your spawn).
2. I checked to see if the lists were spawning somewhere else and could not find a list at my overworld location or anywhere near the portal.

Sidenote, when you cross into the TF and die you spawn next to the portal as your new spawn point.

Thanks for the help!

**Comment by M4thG33k** [comment]
Thanks for the added info! I'll try to work on this tomorrow/this weekend!

**Comment by Darkosto** [comment]
Heya @M4thG33k ! Any luck on the TF integration? :) 

Thanks for your time!

**Comment by M4thG33k** [comment]
@Darkosto Sorry, life has gotten a bit crazy as of late. I'll try to set time aside this week(end) to work on it - please keep bugging me about this until it's done!

**Comment by M4thG33k** [comment]
For those following this thread: Version 1.12-4.0.2 should fix a few issues with the Death Lists (dimension spawning, spawn location, and the deletion when used in the offhand)! (This includes compatibility with TF.)

**Comment by Darkosto** [comment]
Hey @M4thG33k , I'm still having some trouble with my deathlist not showing, I've tried looking around and have no luck finding it on the ground either :(

**Comment by M4thG33k** [comment]
@Darkosto have you set a spawn point already?

**Comment by C0rn3j** [comment]
The Cavern mod has a dimension(which you can reach via Cavenic orb).

https://github.com/kegare/Cavern

In this dimension you should keep XP and items on death. What actually happens is that you keep XP and items go into a grave.

MC 1.12.2 forge 2517, 

Cavern_1.12.1-v1.10.2.jar

TombManyGraves2-1.12-4.0.2

**Comment by Anaerin** [comment]
I have something of an issue. I used an RFTools Matter transmitter to enter an unpowered world (not knowing it was unpowered). It killed me, and a grave dropped (as it should).

I then made a phased field generator (Which stops you from dying in unpowered worlds at the cost of RF), and beamed back to the world. All well and good, until I crouched on the grave. All my items were restored to their original positions, and the phased field generator I was holding was moved into my main inventory (rather than being on my hotbar). At which point I died, because I didn't have the phased field generator on my hotbar.

Is there any way to prevent an item from being moved away?

**Comment by M4thG33k** [comment]
@Anaerin: You should be able to right click the grave to toggle between force/drop modes. (The text shown when staring at the grave will change to indicate this and a chat message should appear too, if I remember correctly. It's been a while since I've worked with that mechanic.)

**Comment by Anaerin** [comment]
That worked perfectly. Thank-you.

**Comment by owen-pi** [comment]
Can you add compatibility for TechGuns 1.12.2 plz? It has an ammo tab, as you can imgine its very annoying to lose your ammo every time u die.

ps woops wrong section, put it in here instead.

**Comment by owen-pi** [comment]
I hate to do this, but our pack is close to going live. 
@M4thG33k Bump bump

**Comment by M4thG33k** [comment]
Just an FYI for anyone posting to this issue: I'm currently in the middle of a move; as soon as it's over, I plan on getting back to bug fixes, etc. Sorry to make you wait!

**Comment by tal985** [comment]
Hi @M4thG33k ,

There's a mod called "Thut Wearables" which functions similarly to the baubles, providing the player additional accessory slots. I was hoping you could add compatibility to TMG.

**Comment by M4thG33k** [comment]
@tal985 I had compatibility working in previous versions of MC; assuming they haven't changed too much, I should be able to do it fairly easily. Again, I'm in the process of moving, so I won't be getting this done for at least a week.

**Comment by Crucial1** [comment]
Please add compatibility with GalactiCraft Mod 1.12.2.

**Comment by M4thG33k** [comment]
Another update to those following this thread: I have my //todo list of mod support and I plan to actively start working on them. Along the same topic, I'm investigating an approach that will make this process more efficient in the future, so I do not have an ETA at this point in time. Just wanted to let you know that I hear you, and I'm working on it (finally...)!

**Comment by NielsPilgaard** [comment]
I'd be grateful for compatibility for the mod Backpacks :)
It adds a backpack slot.
https://minecraft.curseforge.com/projects/forge-backpacks

**Comment by M4thG33k** [comment]
A PSA for those still listening to this thread: I've been working on a new API for TMG that makes plugins easier to make. I am making several plugins that have been requested from players and will release them along with the new version of TMG when they are finished. This also means that this issue will be closed when the new version goes live - new compatibility requests will be made either to the author of the other mod or to a new repo for the plugins I'm developing. It is my goal to have other mod authors write the compatibility into their mod rather than me spending time figuring out their mod when I could spend that time working on my own projects. Thanks for listening!

**Comment by HenryLoenwind** [comment]
Please add compatibility with *Forge*.

Forge has an event where inventories can add items and grave mods can remove items from the list of items to be dropped. You are completely ignoring that and are shitting on any other mod that works with items on death.

PR something better to Forge if you are not happy with the way things are, but don't disable Forge mechanics.

**Comment by QuantumStatement** [comment]
Please add compatibility with [The Camping Mod](https://minecraft.curseforge.com/projects/the-camping-mod)
This mod add custom inventory slots
![img](http://wiki.rikmuld.com/w/images/rikmuld/thumb/1/11/CampingInv-toolsAll.png/500px-CampingInv-toolsAll.png)

**Comment by ResponsibleBear** [comment]
Please add compatibility with Draconic Evolution and soulbound enchant. Tnx.

**Comment by tiffit** [comment]
Closed due to semi-rewrite. New one will be made soon.
