### ISSUE TITLE
[1.11.2][3.0.9] Death lists stop being given to players when they set a spawn.

### ISSUE THREAD

**Issue by Rosethorns** [M4thG33k/TombManyGraves2#10]
If a player sets a bed as spawn then they will stop recieving deathlists when they die.
Also players cannot access the /tmg_getDeathList command unless they are OP

**Comment by mohler7154** [comment]
On my test server the death lists are generating, but appearing at spawn instead of in the players inventory where they set the bed.

**Comment by M4thG33k** [comment]
Sorry for joining the party late (real life has been strange as of late). I'll try to look into these issues today.
