### ISSUE TITLE
Why isn't TMG data saved in the world folder?

### ISSUE THREAD

**Issue by Ricket** [M4thG33k/TombManyGraves2#12]
I noticed there is a new folder created in my modpack's directory, TombManyGraves, which seems to have some saved grave data. Shouldn't this be in the world directory?

**Comment by M4thG33k** [comment]
Because I couldn't for the life of me figure out the path needed to save it to the specific world directory. I decided rather than waste more time figuring it out, that I'd just do what I've done. If you know how to get the path for the world directory, I'll look into changing it up.

**Comment by P3rf3ctXZer0** [comment]
@Thutmose - I know you know this fix.

**Comment by Thutmose** [comment]
I use this:

https://github.com/Thutmose/Thut/blob/1.9/ThutCore/src/main/java/thut/core/common/handlers/PlayerDataHandler.java#L278-L280

**Comment by tiffit** [comment]
Closed due to semi-rewrite.
