### ISSUE TITLE
Grave not placed or items dropped

### ISSUE THREAD

**Issue by Racingmax53** [M4thG33k/TombManyGraves2#14]
I died on a ladder enclosed by stone whilst coming out of a mine.

**Comment by M4thG33k** [comment]
Which version?
Are you 100% sure it didn't spawn? There's a search radius for the grave - it could be placed in any air block within the search radius (outside the ladder shaft).
Are you able to generate a Death List for that death? Have you followed the particles it generates?

**Comment by Racingmax53** [comment]
Version  2.1.16, I have dug out most of the area surrounding and haven't found it. What is the search radius? How do I create a Death List? I haven't seen any particles.

**Comment by M4thG33k** [comment]
Version 2.1.16 is not for this mod. TMG2 starts with version 3.0.0; older versions are not being updated anymore due to time constraints.
