### ISSUE TITLE
4.0.0 not working with 1.12?

### ISSUE THREAD

**Issue by binarybagel** [M4thG33k/TombManyGraves2#15]
Whenever I try to start up the game I get this error:
![tmg](https://user-images.githubusercontent.com/20734190/29750040-d7087652-8b38-11e7-857c-54d31b51c675.png)
Here is also the fml-client-latest.log the error asked me to take a look at:
https://gist.github.com/MainFreak/950da5084b1bffb773f05e0642b3e81e
I hope this is helpful.

**Comment by M4thG33k** [comment]
Weird. I don't have time (at the moment) to figure out why this is happening; for now I've marked the file on Curse to only work with 1.12.1. I'll try to get a version that (actually) works with 1.12 later today.

**Comment by binarybagel** [comment]
Thank you for looking into it! I really enjoyed the mod in 1.10 (and actually waited for a port of it, therefore I didn't use any other grave mod until now :P)

**Comment by M4thG33k** [comment]
Alrighty, 4.0.1 should work with 1.12 now (at least it does for me). If I don't hear any more issues with this in the next few days, I'll close this. :-)

**Comment by binarybagel** [comment]
Yep, it boots up as I expected it to. Feel free to close this,

**Comment by M4thG33k** [comment]
Good news! Thanks for letting me know about the initial issue!
