### ISSUE TITLE
Inventory List is Deleted When Right Clicking while item is held in offhand

### ISSUE THREAD

**Issue by Darkosto** [M4thG33k/TombManyGraves2#16]
Hello!

While holding the inventory list to find my grave, if you right click while holding it in your offhand the item is deleted. It does not seem to be a visual or desync problem. I also tested with only TMG and forge installed, still happens.

MC: 1.12.1
Forge: 2479
TMG: 4.0.1

Thank you!
Darkosto

**Comment by M4thG33k** [comment]
Weird. I'll look into it this weekend if I have the time; I don't consider this "high priority" since you can always give yourself another list via commands
