### ISSUE TITLE
Not Working With Levels Mod

### ISSUE THREAD

**Issue by laiden** [M4thG33k/TombManyGraves2#17]
I am playing around with the Minecraft Reloaded modpack and I wanted to use your grave mod instead of the one in the pack. I disabled the other one, GraveStone Mod, and enabled this one. 1.11.2-3.0.10. I tested it out and after dying I would respawn with my whole inventory and no grave was left. 

In the lastest.log I seen this :
[03:23:22] [Server thread/INFO]: [TombManyGraves]: Laideen died in dimension 0 at BlockPos{x=6, y=79, z=212}. Their grave may be near!
[03:23:22] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDeathEvent@54e4e1:
java.lang.NoClassDefFoundError: com/thexfactor117/levels/leveling/Attribute
	
So I disabled the Levels mod, 2-1.11.2-r1.2.8, tried again and now it works perfect. It would seem there is some sort of issue with Levels. I've attached a bit more of the log if that helps.

I apologize if I'm missing something on my end but I can't find anything in config files or so. I cannot find any mention of this either, which I find strange... making me think that it is something I'm doing wrong. 

Thanks for the time and effort put into this mod!

[Tomb Many Graves_Levels.txt](https://github.com/M4thG33k/TombManyGraves2/files/1327115/Tomb.Many.Graves_Levels.txt)

**Comment by laiden** [comment]
My fault for not reading into the first post about incompatibilities more. Somewhere in the post Levels is mentions and you said it would be coming in the next update for 1.11.2. 

Sorry for the post. Nothing came up in any searches.

**Comment by M4thG33k** [comment]
The 1.11.2-3.0.10 Version added compatibility with the most recent version of Levels at the time (3.11.2-3.0.2-beta). I don't plan on working on adding features for versions below 1.12 at this time due to time constraints. Sorry.
