### ISSUE TITLE
I Was Told To Notify You Of This Bug!

### ISSUE THREAD

**Issue by Darkosto** [M4thG33k/TombManyGraves2#19]
https://clips.twitch.tv/SweetCooperativeOpossumStinkyCheese

^^ This is what happens when you report bugs by yelling! 

xD

**Comment by M4thG33k** [comment]
Looks like my minions are still working hard to destroy all evidence of bugs. 

But in all seriousness, how did you get that grave block? Was it picked up as an item somehow?

**Comment by JamiesWhiteShirt** [comment]
Why does an ItemBlock for the grave even exist? If you don't register an ItemBlock for it, it will never appear and everything should be fine.

**Comment by M4thG33k** [comment]
I'm sure I had a reason way back when I first created it. I'll look into it sometime this week if I have an opportunity.

**Comment by Kaelthalon** [comment]
Oh hey! Same thing happened to me in Darkosto's pack. I got mine after I died to a creeper explosion.

**Comment by ginkoopl** [comment]
I picked up the block in SevTech: Ages just by pressing shift on it.

**Comment by enki1337** [comment]
+1; Death by creeper explosion, if that helps any.
