### ISSUE TITLE
rpg inventory compat(1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [M4thG33k/TombManyGraves2#23]
when i died its doesnt save any of my cloaks from rpg inventory

Forge:1.12.2-2575
TMG2:1.12.2-4.0.5

heres the mod if you need to know any details etc https://minecraft.curseforge.com/projects/the-rpg-inventory-and-classarmor-mod?gameCategorySlug=mc-mods&projectID=251752

**Comment by tiffit** [comment]
Closed due to semi-rewrite.
