### ISSUE TITLE
MineColinies Official Modpack

### ISSUE THREAD

**Issue by janagyjr** [M4thG33k/TombManyGraves2#25]
I'm unable to retrieve my grave (MC 1.12.2 forge 2555, TMG2 1.12-4.0.2). I've looked through the config and nothing seems awry but I'm more familiar with another gravestones mod. I've sneaked next it, 'on' it, below it (one block below, it formed over a piece of carpet). I've tried jumping, breaking, etc. to no luck.

https://gist.github.com/janagyjr/6eba9b732864505d4a0fb355591ddc51 - cfg distributed with MineColonies Official pack (I thought about opening an issue there, but I'm not sure if it's a pack issue or not)

**Comment by M4thG33k** [comment]
Are you sure the grave isn't "locked"? This prohibits users from retrieving the grave. Either right-click or sneak  & right-click to toggle the locked status - it's been a while and I can't remember which it is a this point :-/

**Comment by janagyjr** [comment]
I'm 99% certain it's not locked, however, I'm OP on the server so it shouldn't matter?

**Comment by janagyjr** [comment]
I'll check shortly.

**Comment by janagyjr** [comment]
I feel like an idiot now. Thanks and sorry to clutter up the issue tracker. :-/
