### ISSUE TITLE
[3.0.2] Grave unapproachable. Causes client crash

### ISSUE THREAD

**Issue by Rosethorns** [M4thG33k/TombManyGraves2#3]
A player on the server has died and no one can approach their grave without crashing. This is the first time this particular issue has happened. So its not easily reproducible. But here is the crash log.

https://pastebin.com/pRYdV24J

We tried getting the player whos grave it is to change back to the steve skin, and we also tried changing it to skull and forced dirt base.

Both were a no go.

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2260
TMG: 3.0.2

**Comment by M4thG33k** [comment]
Well that's very bad. I'll try to get a fix figured out after class today.

**Comment by M4thG33k** [comment]
@Rosethorns I have build 3.0.3 uploading to Curse as I type this. I believe I've added sufficient exception handling to stop the crashes (of course, I've thought this before, so who knows?) Please let me know if this fixes the issue you've had. I also added a config to disable the rendering of graves (skulls) completely (has to be set on the client side, of course) as well as a new command: "/tmg_toggle_render" which toggles the aforementioned config (temporarily - it will default back to the config setting when restarting the client). Enjoy! :-)

**Comment by Rosethorns** [comment]
So It sort of worked :P The grave is not crashing anyone anymore. However instead now the grave is your grave as in M4thG33k's and cannot be retrieved. Thoughts?

**Comment by M4thG33k** [comment]
Interesting; I have myself hard-coded as grave owners in case people are using hacked versions of the game and it can't find their player data online. But I'll try to add in some admin commands to allow grave ownership changing and/or grave destruction. Give me a few hours. ;-)

**Comment by M4thG33k** [comment]
@Rosethorns Version 3.0.4 going live now. Three commands added (hopefully this will help the problem):

### /tmg_toggle_grave_pos 
Toggles whether or not graves show their block position when looking at them (useful if players need to relay this information to an admin)

### /tmg_pop_grave [x] [y] [z]
Deletes the grave at the given location and drops all stored items at that spot. Only players with permission level 2 or higher can use this command.

### /tmg_steal [x] [y] [z]
Changes the owner of a grave at the given location to the user of the command. Only players with permission level 2 or higher can use this command.

Please let me know if anything else pops up!

**Comment by Rosethorns** [comment]
Thats fantastic thank you so much!

**Comment by M4thG33k** [comment]
I'm assuming I may close this issue now? I haven't heard of any new problems. :-)

**Comment by Rosethorns** [comment]
Oh. Uh. Yes! no problems found since :3
