### ISSUE TITLE
FPS drops to 8 when looking in the direction of the grave.

### ISSUE THREAD

**Issue by ginkoopl** [M4thG33k/TombManyGraves2#31]
Hello, my fps drops extremely low every time I look at mine or my friend's grave, I often see nearby items, monsters or blocks on my screen when that happens (example in the screenshot, it's like all the water from loaded chunks just raised into the air). I haven't found any mention of this issue anywhere so I thought I'll try my luck here.

It happens on SevTech: Ages modpack on AT launcher. I should probably mention that it only happens to me and not my friend.

![2018-04-07_11 49 43](https://user-images.githubusercontent.com/38177621/38464961-8ad154e8-3b1e-11e8-9b08-30f2d30d5f91.png)

**Comment by M4thG33k** [comment]
Yeah, I've never had anyone else report any issue like this. I'll keep this open in case others run into the problem, but it'll be difficult to fix without being able to reproduce it myself.

**Comment by tiffit** [comment]
Closed due to semi-rewrite.
