### ISSUE TITLE
[Suggestion]Galacticraft Support

### ISSUE THREAD

**Issue by SihenZhang** [M4thG33k/TombManyGraves2#33]
When I died at planets in Galacticraft or other addon mods, I will lost my Galacticraft Armor and I will die again. 

So **could you please add Galacticraft support**? I'll appreciate it if you can do that.

**Comment by M4thG33k** [comment]
I'll see what I can do. No ETA at the moment, of course, but know that it's on my //todo list!

**Comment by tiffit** [comment]
Closed due to semi-rewrite.
