### ISSUE TITLE
Mod Support Request

### ISSUE THREAD

**Issue by justinrusso** [M4thG33k/TombManyGraves2#34]
I would really love if these mods were supported:

Baubles (If not supported)
Galacticraft (#33)
The Betweenlands

We've had players in SevTech get a bit  frustrated they lost items thinking they would be in the grave, but later learned they de-spawned from it not being caught by the gravestone.

**Comment by M4thG33k** [comment]
To help speed up adding support for GC and The Betweenlands (when I get to that point), what types of inventories do the mods add that the grave isn't taking into account? This saves a bit of time for me digging through code in attempt to discover them on my own (as I haven't played with either mod). Thanks!

**Comment by M4thG33k** [comment]
Working on compatibility - besides amulets/rings for The Betweenlands, is there any other inventory the mod adds that I'm unaware of?

**Comment by justinrusso** [comment]
There is also a sack that is similar to a backpack.

GC adds a new tab when viewing inventories for a different "style" of armor and a few other additions there as well.

**Comment by M4thG33k** [comment]
I got it all worked out. Thanks! I should have updates out later this week.

**Comment by vadis365** [comment]
Awesome - thanks ;)

**Comment by Renari** [comment]
Looking forward to this, we had a few people lose betweenlands accessories which are fairly hard to get (requires exploring to find and kill bosses). They were fairly upset to learn that it just throws the accessories on the ground.

**Comment by justinrusso** [comment]
They will also be upset knowing that any of their existing graves will be broken.
