### ISSUE TITLE
[SUGGESTION] Implement the capacities of Tomb Many Plugins into this mod

### ISSUE THREAD

**Issue by Sunconure11** [M4thG33k/TombManyGraves2#36]
I do not believe there is a point in having them segregated from the main mod; instead, their functionality should toggle depending on what mods are installed. There are ways of picking up such things without using another mod entirely. I'd advise sifting through the codebases of various mods with cross-compat with one another.

Totemic, while being an entirely separate mod, manages to accomplish this by looking for the ID of said mod.

https://github.com/TeamTotemic/Totemic/blob/1.12.2/src/main/java/pokefenn/totemic/ceremony/CeremonyBuffaloDance.java

The mod I've been working on also does something similar, for checking for potion effects.

https://github.com/Um-Mitternacht/Bewitchment/blob/master/src/main/java/com/bewitchment/common/potion/potions/brews/PotionSinking.java

There are obviously other examples, I'd advise looking around, because I feel the plugin system is redundant except for third-party devs.

**Comment by tiffit** [comment]
Closed due to semi-rewrite.
