### ISSUE TITLE
Command line Timestamp

### ISSUE THREAD

**Issue by soleofdeath** [M4thG33k/TombManyGraves2#37]
What is the timestamp layout? for /tmp_restore player timestamp I've tried all examples of timestamps and non of them have worked

**Comment by M4thG33k** [comment]
I don't remember off the top of my head, but you can use [TAB] to auto-complete commands (it should display all available files). If it doesn't work for the restore command, I know it works for the /tmg_deathlist command

**Comment by soleofdeath** [comment]
thanks
