### ISSUE TITLE
Deprecated Graves support

### ISSUE THREAD

**Issue by justinrusso** [M4thG33k/TombManyGraves2#38]
**Request Description**
Deprecated graves do not gracefully upgrade.

**Suggested Solution**
A way for the deprecated graves to support the new code.

**Additional context**
Without supporting the deprecated graves in some way that allows the player to obtain all content from their old grave, the 4.1.0 update is literally something we cannot upgrade to.

**Comment by M4thG33k** [comment]
The only reason you need to update to 4.1.0 in an existing world is if you need any of the new mod compatibilities added by a plug-in. I also put in the change log on Curse that the new update would not be 100% compatible with the previous version. I will not be adding this support at this time.

**Comment by justinrusso** [comment]
Correct, and we do need to update. I had asked for the support for multiple mods, and now we cannot use them without ruining potentially thousands of player's games. I read the changelog, that's exactly why I am here requesting for support otherwise.
