### ISSUE TITLE
/tmg_restore does not work if player is renamed

### ISSUE THREAD

**Issue by coledot** [M4thG33k/TombManyGraves2#39]
**Describe the bug**
A player on our multiplayer server has since renamed their Minecraft account after the last time they died & generated a grave. Now that the user is under a different name, /tmg_restore no longer works and gives the error "Either the owning or receiving player is offline." I have tried both renaming the file on the server as well as editing the JSON to contain the new username in place of the old one, but neither seems to work; same error.

It may also be worth noting, this player's graves were generated during the Twilight Forest hydra fight, so the graves themselves are no longer accessible.

Modpack: Enigmatica 2: Expert 1.30
Mod version: Tomb Many Graves 4.1.0

**To Reproduce**
1. Die & generate a grave.
2. Rename your Minecraft account.
3. Attempt to restore your grave with /tmg_restore.

**Expected behavior**
An op should be able to use /tmg_restore to restore the player's inventory.

**Comment by tiffit** [comment]
Closed due to semi-rewrite.
