### ISSUE TITLE
[1.11.2 - 3.0.3] Cosmetic Armors not compatible

### ISSUE THREAD

**Issue by VallenFrostweaver** [M4thG33k/TombManyGraves2#4]
Currently Cosmetic Armor Reworked (v1a) and TMG (v3.03) are not working together. Any cosmetic armors are dropped on the ground.
![grave](https://cloud.githubusercontent.com/assets/13642054/24611594/91c4c374-187a-11e7-8d86-3d3cd258d6a7.png)

**Comment by M4thG33k** [comment]
I'll see if I can add compatibility today. Thanks!

**Comment by VallenFrostweaver** [comment]
No worries. Thank _you_ for a great mod. :)

**Comment by M4thG33k** [comment]
Version 3.0.5 should have compatibility working. :-) Please open a new issue if problems arise, and thanks for letting me know that CosArmor had updated to 1.11.2!
