### ISSUE TITLE
Mod no longer maintained

### ISSUE THREAD

**Issue by M4thG33k** [M4thG33k/TombManyGraves2#41]
As of July 2018, I (M4thG33k) have decided to stop updating this mod.

The code will, of course, remain available. If someone else wishes to continue the work on the mod, feel free to do so. I'd hate to see the mod vanish completely (even if I don't have a hand in it), but I, sadly, do not have the time to keep up with the game anymore.

**Comment by NielsPilgaard** [comment]
Thank you for all your hard work, it is greatly appreciated :)
