### ISSUE TITLE
death locations are persistent across all worlds.

### ISSUE THREAD

**Issue by BannerBomb** [M4thG33k/TombManyGraves2#56]
**Describe the bug**
I am on  minecraft 1.12.2 forge (modded) forge-14.23.5.2847

When i create a new world after I died in a previous one, it still shows the death location from the previous world. No matter if I delete the previous world and recreate another one. 
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11788894/77224432-04be1f80-6b3c-11ea-9bc3-34b00132c946.png)

**Additional context**

**Comment by BannerBomb** [comment]
the world is completely new, and as you can see it shows my death from on a previous world which happened yesterday

**Comment by SoraHjort** [comment]
Those waypoints are handled by JourneyMap mod, not Tomb Many Graves 2. 

You can go into Journeymap and delete the waypoints from in there.
