### ISSUE TITLE
Make config option to disable death log showing location of player's death in chat

### ISSUE THREAD

**Issue by Konlii** [M4thG33k/TombManyGraves2#6]
Similar to the config option to disable the death log in the server log, please add a config option to disable the chat that shows location of the player's death at the moment of death.

I am also using the [DeathShot](https://minecraft.curseforge.com/projects/deathshot) mod which takes a screenshot when you die and the death location chat is showing up in those screenshots.  Since that information is already in the Death Inventory List, what purpose does the chat serve?

**Comment by M4thG33k** [comment]
I can definitely add a config for that. The chat messages are nice in case you get sidetracked on your way to finding a grave and lose the list and/or die several times, then you can look back in the logs and find the location. It's more a debugging tool as well, so adding a config to disable wouldn't be a bad thing. Thanks for suggesting it!

**Comment by Konlii** [comment]
Awesome! This is the best grave mod I have ever used, hands down.

But you're right, I have noticed that if I die on the way to a grave the new grave doesn't include the previous list even though it was in my inventory.

**Comment by M4thG33k** [comment]
Yeah, lists are not allowed in graves. If they are allowed, there is a good possibility of NBT overflow (too much data attempting to be stored in a grave) which causes crashes. (Imagine dying with a list in your hand, the new list has the data of the old list. Now you die with that list and the new list has the data from both old lists. If this pattern continues, the size of the data on the list grows exponentially. That is very bad.)

**Comment by Konlii** [comment]
Oh, I didn't realize that the list itself held that kind of information about the grave contents. I thought that would stay in the grave tile entity itself. I have tested purposefully making multiple lists that lead to different graves and they work perfectly as long as I put the first list in a chest first.

**Comment by M4thG33k** [comment]
Yeah, the lists contain the exact same data as the grave (so it can display the location, time stamp, player, and contents without actually probing the grave for the information).

EDIT: But since you can always use commands to get old lists back, I don't think this is too much of an issue.
