### ISSUE TITLE
Items lost when grave not placed

### ISSUE THREAD

**Issue by Doragoon01** [M4thG33k/TombManyGraves2#7]
I died and received the message that there was no valid place for the grave.  but when i went back to where i died, the items hadn't been dropped either.  Would be nice if it was kinda one or the other.

**Comment by M4thG33k** [comment]
Oops. Looks like I missed a bit of logic when I re-wrote the mod; you're correct - it _should_ either collect the items into a grave or drop them on the ground, but I forgot to implement the second portion of that. I'll try to get a fix out tomorrow. Thanks for bringing this to my attention!
