### ISSUE TITLE
compat problem with inventory pets // also crash

### ISSUE THREAD

**Issue by Chromogen** [M4thG33k/TombManyGraves2#8]
tmg will not place a grave with inventory pets death handler (there is a gravepet)
tried with 'gravestone mod' instead, worked fine. so i guess it is  more or less on tmg :/

Version:
inventorypets-1.11.2-1.4.9.5
TombManyGraves-1.11.2-3.0.7

crash report:
https://pastebin.com/Yq8pM8Yj

**Comment by M4thG33k** [comment]
Well, it looks like Inventory Pets updated and changed how they dealt with the grave pet which broke the compatibility I already had in place. :-/ I'll try to get a fix out tomorrow.

**Comment by Chromogen** [comment]
posted the report on his side too :)

**Comment by M4thG33k** [comment]
I've also reached out to Purplicious_Cow to see what changes were made. :-)

**Comment by Chromogen** [comment]
what s left to say is thank you very much!
(also i love your mod)

**Comment by M4thG33k** [comment]
Thank you for playing with the mod and for bringing this issue to my attention! :)

**Comment by capnkirok** [comment]
For the record, this was entirely my fault as I refactored the code without letting @M4thG33k . Thanks for the quick work 👍

**Comment by Chromogen** [comment]
thx alot :)
