### ISSUE TITLE
wired stuff with modinteraction (cyberware)

### ISSUE THREAD

**Issue by Chromogen** [M4thG33k/TombManyGraves2#9]
okay i now got a very special report for you

when you happen to have cyberware installed, it gives you a defibrilator which will revive you if you die.
but the fun thing is that your mod will still create a grave.

mod
Cyberware-1.11.2-alpha-0.2.9
TombManyGraves-1.11.2-3.0.8
Forge-13.20.2.2302

**Comment by M4thG33k** [comment]
Let me make sure I understand this correctly: Cyberware adds an item which (assuming you have it on your person upon death), basically "cancels" death? Assuming that is what's happening, then my grave is probably doing its logic before Cyberware, resulting in the grave (and I'm assuming you'll still die). Is this what's happening?

**Comment by Chromogen** [comment]
pretty much yes. your mod kicks in before the death-prevention of cyberware so your items will be saved in a grave leaving you alive but with empty inventory. so its no bug just a compat thing :)

cyberware adds a function like baubles with a sideslot for its special trait items which will stay on you no matter if you die or not. no problem there :)

**Comment by M4thG33k** [comment]
I'm thinking of trying this fix (later...not today): If Cyberware is installed, have the grave check for the existence of the defibrillator; if it exists, cancel grave logic - if it doesn't, continue with grave placement. Do you believe that will work? (I haven't done any testing myself, I'm just trying to get as much info before I work on it.) Thanks!

**Comment by Chromogen** [comment]
the mod is about implanting stuff in your body. what you do is feed an item to a machine and it gets implanted to your body. so i have no clue if it is any kind of side inventory. more likely its written in player NBT

i also did not test if the defi stays on you when you die / when it kicks in it gets used up.

would recommend to ask the devs for more info :/



Edit:
got some spare time. will investigate NBT

**Comment by Chromogen** [comment]
found something! its in the player data.
level.dat>Player>ForgeCaps>cyberware:cyberware>cyberware
then there is a long list of grouped entries.... not sure if i got the correct one since normal bodyparts will get its own entries (this mod lets you remove and replace almoast all body party ^^;)

but hey, there is this one
found by comparing with and without the defi on character installed

```
level.dat>Player>ForgeCaps>cyberware:cyberware>cyberware
Count: 1
Damage: 0
id:cyberware:heart_upgrades
```

and i also tested: it will get used up on death...but!
you got some kind of internal energy count. and you need 600 of this to actually trigger this defi
this is also in NBT:

`level.dat>Player>ForgeCaps>cyberware:cyberware>storedPower: XXX`

this value must be 500 or highter to trigger the defi




so... i d suggest to check those. defi AND power >500 AND death

what a nuisance! xD

**Comment by Chromogen** [comment]
nice one :D

**Comment by M4thG33k** [comment]
I did a little testing with it, but if it doesn't work in some odd case, let me know so I can fix it (again). :smile:
